services:
  postgres:
    image: postgres:17.2
    container_name: postgres-db2
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stripe-db
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge